# Generated by Django 5.2 on 2025-10-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "categories_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("categories_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField(blank=True, null=True)),
                ("total_invoice", models.FloatField()),
                ("create_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                (
                    "product_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("base_price", models.FloatField()),
                ("shelf_life", models.IntegerField()),
                ("is_active", models.BooleanField()),
                ("update_by", models.CharField(max_length=100)),
                ("update_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "product_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("product_type_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StatusMaster",
            fields=[
                ("status_code", models.AutoField(primary_key=True, serialize=False)),
                ("status_name", models.CharField(max_length=100)),
                ("update_by", models.CharField(max_length=100)),
                ("update_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.FloatField()),
                ("quantity_product", models.IntegerField()),
                ("create_at", models.DateTimeField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.orders",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.productmaster",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productmaster",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="first_app.producttype"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="first_app.statusmaster"
            ),
        ),
        migrations.CreateModel(
            name="TableMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.statusmaster",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="first_app.tablemaster"
            ),
        ),
        migrations.CreateModel(
            name="CategoriesProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField()),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.categories",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.productmaster",
                    ),
                ),
            ],
            options={
                "unique_together": {("categories", "product")},
            },
        ),
    ]
