# Generated by Django 5.2 on 2025-10-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaster",
            name="shelf_life",
        ),
    ]
