# Generated by Django 5.2 on 2025-10-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_remove_productmaster_shelf_life"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaster",
            name="product_type",
        ),
        migrations.AlterField(
            model_name="productmaster",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
    ]
