# Generated by Django 5.2 on 2025-10-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_remove_productmaster_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaster",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
