# Generated by Django 5.2 on 2025-10-16 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0004_alter_productmaster_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("update_by", models.CharField(max_length=100)),
                ("update_time", models.DateTimeField()),
                (
                    "productdetail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="first_app.productmaster",
                    ),
                ),
            ],
        ),
    ]
