# Generated by Django 5.2 on 2025-10-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0005_alter_productmaster_is_active_productdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productdetail",
            old_name="productdetail",
            new_name="product_code",
        ),
    ]
