# Generated by Django 5.2 on 2025-10-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0006_rename_productdetail_productdetail_product_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="customer_id",
        ),
    ]
