# Generated by Django 5.2 on 2025-10-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0007_remove_orders_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetail",
            name="product_code",
        ),
        migrations.AddField(
            model_name="productmaster",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="first_app.categories",
            ),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CategoriesProduct",
        ),
        migrations.DeleteModel(
            name="ProductDetail",
        ),
    ]
