# Generated by Django 5.2 on 2025-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0008_remove_productdetail_product_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablemaster",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
