# Generated by Django 5.2 on 2025-10-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0009_tablemaster_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablemaster",
            name="status",
        ),
    ]
