# Generated by Django 5.2 on 2025-10-25 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0010_remove_tablemaster_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partnerCode", models.CharField(max_length=50)),
                (
                    "requestId",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "orderId",
                    models.CharField(default=uuid.uuid4, max_length=200, unique=True),
                ),
                ("orderInfo", models.CharField(blank=True, max_length=255)),
                ("redirectUrl", models.URLField()),
                (
                    "requestType",
                    models.CharField(default="captureWallet", max_length=50),
                ),
                ("extraData", models.TextField(blank=True)),
                ("lang", models.CharField(default="vi", max_length=2)),
                ("signature", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name="productmaster",
            old_name="image",
            new_name="imageUrl",
        ),
        migrations.RenameField(
            model_name="productmaster",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="base_price",
        ),
        migrations.AddField(
            model_name="productmaster",
            name="currency",
            field=models.CharField(default="VND", max_length=10),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="price",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="totalPrice",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="first_app.order"
            ),
        ),
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
