# Generated by Django 5.2 on 2025-10-25 07:32

import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0011_order_rename_image_productmaster_imageurl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderId",
            field=models.CharField(
                default=first_app.models.generate_order_id, max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="requestId",
            field=models.CharField(
                default=first_app.models.generate_request_id, max_length=50, unique=True
            ),
        ),
    ]
