# Generated by Django 5.2 on 2025-10-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0012_alter_order_orderid_alter_order_requestid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmaster",
            old_name="name",
            new_name="product_name",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="quantity_product",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="totalPrice",
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="totalPrice",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="productmaster",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
