# Generated by Django 5.2 on 2025-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0013_rename_name_productmaster_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="imageUrl",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
