# Generated by Django 5.2 on 2025-10-28 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0014_categories_imageurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="first_app.tablemaster",
            ),
        ),
    ]
