# Generated by Django 5.2 on 2025-10-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0015_order_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="first_app.statusmaster",
            ),
        ),
    ]
