# Generated by Django 5.2 on 2025-10-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0017_customer_deliveryarea_order_customer_customer_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="area",
        ),
        migrations.DeleteModel(
            name="DeliveryArea",
        ),
    ]
