# Generated by Django 5.2 on 2025-10-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0018_remove_customer_area_delete_deliveryarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
