# Generated by Django 5.2 on 2025-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0019_alter_customer_address_alter_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
