# Generated by Django 5.2 on 2025-11-01 07:45

import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0020_order_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=first_app.models.generate_order_id, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
