# Generated by Django 5.2 on 2025-11-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0021_order_order_id_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
