# Generated by Django 5.2 on 2025-11-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0022_customer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
    ]
