# Generated by Django 5.2 on 2025-11-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0023_remove_order_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="extraData",
        ),
    ]
