# Generated by Django 5.2 on 2025-11-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0024_remove_order_extradata"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="extraData",
            field=models.TextField(blank=True),
        ),
    ]
