# Generated by Django 5.2 on 2025-11-14 03:45

import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0025_order_extradata"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=first_app.models.generate_order_id, max_length=100
            ),
        ),
    ]
