# Generated by Django 5.2 on 2025-11-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0029_order_extradata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablemaster",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
