# Generated by Django 5.2 on 2025-12-07 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0030_alter_tablemaster_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "material_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("material_name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inventory",
                        serialize=False,
                        to="first_app.material",
                    ),
                ),
                ("quantity", models.FloatField(default=0)),
                ("min_quantity", models.FloatField(default=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_required", models.FloatField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="first_app.material",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="first_app.productmaster",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "material")},
            },
        ),
    ]
