# Generated by Django 5.2 on 2025-12-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0031_material_inventory_productmaterial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="description",
        ),
    ]
