# Generated by Django 5.2 on 2025-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0032_remove_material_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
