# Generated by Django 5.2 on 2025-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0033_alter_material_material_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
