# Generated by Django 5.2 on 2025-12-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0036_remove_supplier_supplier_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="first_app.supplier",
            ),
        ),
    ]
