# Generated by Django 5.2 on 2025-12-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0037_alter_purchaseorder_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockin",
            name="supplier",
        ),
    ]
