# Generated by Django 5.2 on 2025-12-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0038_remove_stockin_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
