# Generated by Django 5.2 on 2025-12-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0039_alter_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totalquantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
