# Generated by Django 5.2 on 2025-12-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0042_remove_productmaster_totalquantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="totalquantity",
        ),
        migrations.AddField(
            model_name="productmaster",
            name="totalquantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
