# Generated by Django 5.2 on 2025-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0043_remove_order_totalquantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaster",
            name="product_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
