# Generated by Django 5.2 on 2025-12-29 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0044_alter_productmaster_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaster",
            name="product_name",
            field=models.CharField(
                default=1,
                max_length=255,
                validators=[django.core.validators.RegexValidator(regex="[A-Za-zÀ-ỹ]")],
            ),
            preserve_default=False,
        ),
    ]
