# Generated by Django 5.2 on 2026-01-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0045_alter_productmaster_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaster",
            name="totalquantity",
        ),
    ]
